### ISSUE TITLE
Definir Modelo de Entidade e Relacionamento(DER)

### ISSUE THREAD

**Issue by athosburlamaqui** [AquilesBurlamaqui/monitoria#17]
Modelar o banco de dados e definir suas tabelas

**Comment by maaamorim** [comment]
[Imagem](https://www.dropbox.com/s/ehbfrl0meri3cfp/prototipo-der.jpg?dl=0)
Protótipo de DER feito no MySQL Workbench baseado na seguinte wiki:
- Login
- Cadastro de Usuário
- Criação de problemas
- Criação de soluções
- Comentários das soluções;
- Avaliação das soluções;
- Sistema de tags/keywords;
